language: php

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

php:
  - 5.6.4
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=5.4.*
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.6.*
  - LARAVEL_VERSION=5.7.*

matrix:
  fast_finish: true
  exclude:
    - php: 5.6.4
      env: LARAVEL_VERSION=5.5.*
    - php: 5.6.4
      env: LARAVEL_VERSION=5.6.*
    - php: 5.6.4
      env: LARAVEL_VERSION=5.7.*
    - php: 7.0
      env: LARAVEL_VERSION=5.6.*
    - php: 7.0
      env: LARAVEL_VERSION=5.7.*
    - php: 7.2
      env: LARAVEL_VERSION=5.4.*
    - php: 7.3
      env: LARAVEL_VERSION=5.4.*

before_install:
  - travis_retry composer self-update --stable -n
  - composer validate --no-check-all --strict
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o
  - composer update

script:
  - vendor/phpunit/phpunit/phpunit
